# Generated by Django 2.2.1 on 2019-05-23 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiverrapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='gig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiverrapp.Gig'),
        ),
        migrations.AlterField(
            model_name='review',
            name='gig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiverrapp.Gig'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
