# Generated by Django 2.2.1 on 2019-05-23 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fiverrapp', '0002_auto_20190523_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
